### ISSUE TITLE
【Q&A】ezm 与 devtoolx 上面显示的内存大小不一致

### ISSUE THREAD

**Issue by xiaoxiaojx** [noslate-project/devtoolx#17]
- 问题: 大佬你好，麻烦问一下为啥 ezm 下载的内存快照在 devtoolx 或者 Chrome devtool 上面显示的内存占用与 ezm 上面显示的有较大区别，这个可能是啥原因
![image](https://user-images.githubusercontent.com/23253540/216257446-2ceb85d9-9c15-4e54-8ab8-8d189ac13d15.png)
![image](https://user-images.githubusercontent.com/23253540/216257582-7c5dc7b4-e73f-4241-af08-cf8a763b2115.png)

**Comment by hyj1991** [comment]
`heapdump` 前 v8 会做一次 full gc 的

**Comment by xiaoxiaojx** [comment]
哦哦，原来如此，多谢解答～
